# Generated by Django 3.1.7 on 2021-04-17 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('game_id', models.IntegerField(default=None)),
                ('genres', models.JSONField()),
                ('released', models.CharField(max_length=100, null=True)),
                ('description_raw', models.TextField(null=True)),
                ('background_image', models.ImageField(upload_to='static/images')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('metacritic', models.IntegerField(default=None, null=True)),
                ('esrb_rating', models.CharField(max_length=100, null=True)),
                ('slug', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('favorite_games', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_date', models.DateField(default=django.utils.timezone.now)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('rating_score', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='capstone_app.game')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
