# Generated by Django 3.1.7 on 2021-04-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='game',
            name='esrb_ratings',
        ),
        migrations.RemoveField(
            model_name='game',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='game',
            name='total_rating',
        ),
        migrations.AddField(
            model_name='game',
            name='game_id',
            field=models.IntegerField(default=None),
        ),
    ]
