# Generated by Django 3.1.7 on 2021-04-18 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0002_auto_20210417_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='about',
            field=models.TextField(null=True),
        ),
    ]
