# Generated by Django 3.1.7 on 2021-04-18 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0003_player_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamereview',
            old_name='body',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='gamereview',
            old_name='title',
            new_name='review',
        ),
    ]
