# Generated by Django 3.1.7 on 2021-04-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0004_auto_20210418_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='favorite_games',
        ),
        migrations.AddField(
            model_name='player',
            name='favorite_games',
            field=models.ManyToManyField(null=True, to='capstone_app.Game'),
        ),
    ]
