# Generated by Django 3.1.7 on 2021-04-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0007_auto_20210418_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='favorite_games',
            field=models.ManyToManyField(blank=True, to='capstone_app.Game'),
        ),
    ]
