# Generated by Django 3.1.7 on 2021-04-18 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_app', '0008_auto_20210418_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='favorite_games',
        ),
        migrations.AddField(
            model_name='player',
            name='favorite_games',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='capstone_app.game'),
        ),
    ]
